---
title: "Scraping Mobile Legends data"
author: "Rafal Nowicki"
date: "7 04 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xml2)
library(rvest)
library(jsonlite)
library(robotstxt)
library(RSocrata)
library(tidyr)
library(splitstackshape)
library(tidyverse)
library(magrittr)
```


## 1. Scraping character names

```{r}

url.char <- read_html("https://mobile-legends.fandom.com/wiki/Category:Heroes")

nds.char <- html_nodes(url.char, 
                       xpath = '//*[contains(concat( " ", @class, " " ),
                       concat( " ", "category-page__member-link", " " ))]')

chars <- html_text(nds.char) %>% sort()

pattern = "Hero|Squad|Category|Support|Fighter|Assassin|Mage|Tank|Marksman|Skins|Popol|Luo"

idx <- which(str_detect(chars, pattern))

chars.legit <- c(chars[-idx], "Masha", "Yi_Sun-Shin", "Carmilla", "Cecilion") %>%
  str_replace("Chang'e", "Chang%27e")%>%
  sort()
```

## 2. Scraping characters skills

```{r}
chars.skills <- list()
n.chars <- length(chars.legit)

for (i in 1:n.chars){
  url.skills <- read_html(paste0("https://mobile-legends.fandom.com/wiki/", chars.legit[[i]]))
  
  nds.skills <- html_nodes(url.skills, 
                           xpath = '//*[contains(concat( " ", @class, " " ),
                           concat( " ", "hero-attributes", " " ))]//table')
  
  char.info <- html_text(nds.skills)
  
  skills.set <- char.info
  
  
  chars.skills[[i]] <- skills.set
}
```

## 3. Skills data wrangling

```{r}
pattern2 <- "Magic Resistance |Movement Speed |Mana |Physical Attack |Attack Speed |Magic Power |HP Regen |Physical Defense |Mana Regen |Magical Defense |Basic Attk Crit Rate |HP |Ability Crit Rate |Armor |Regen "

chars.skills.df <- chars.skills

chars.skills.df %<>%
  unlist() %>% 
  str_replace_all("-", "0") %>%
  str_replace_all(pattern2, "") %>%
  trimws() %>%
  as.data.frame() %>%
  cSplit(1:ncol(.), sep=" ",
         stripWhite=TRUE, type.convert=FALSE) %>%
  as.data.frame() %>%
  set_colnames(c("MV_SPD", "MANA", "P_ATK", "ATK_SPD", "M_PWR",
               "HP_RGN", "P_DFN", "MANA_RGN", "MGC_DFN", "ATK_CR", "HP", "AB_CR")) 
```


```{r, echo = FALSE, include = FALSE}
#Some manuall corrections for empties and mistakes

chars.skills.df[c(9,10,15,16,25,47,69,70,87,90),4] <- c(0.8,0.908,NA,NA,0.8,0.826,0.814,0.864,0.8,0.8)
chars.skills.df[c(25,43,47,75,90,91),1] <- c(240,260,255,240,240,240)
chars.skills.df[65,c(3,4,5,6,7,8,9,10,11,12)] <- c(NA,NA,0,19,12,0,10,0,1948,NA)
chars.skills.df[c(2,22),5] <- c(0,NA)
chars.skills.df[10,3] <- 119
```

## 4. Scraping roles data
```{r}
chars.roles.mat <- matrix(ncol = 1, nrow = n.chars)

for (i in 1:n.chars){
  url.skills <- read_html(paste0("https://mobile-legends.fandom.com/wiki/", chars.legit[[i]]))
  
  nds.skills <- html_nodes(url.skills, 
                           xpath = '//*[contains(concat( " ", @class, " " ),
                concat( " ", "font-size-11", " " ))]//a')
  
  char.role <- html_text(nds.skills)
  
  chars.roles.mat[i,1] <- char.role[[1]]
}

colnames(chars.roles.mat) <- "ROLE"
```

## 5. Combining the data and exporting the file

```{r}
df_scrape <- data.frame(Id = 1:n.chars, HERO = chars.legit, 
                        data.matrix(chars.skills.df), chars.roles.mat) %>%
  select(-c("ATK_CR", "AB_CR"))

df <- df_scrape[,c(1,2,3,11,4,8,5,9,12,6,10,13)]%>%
  as_tibble() %>% arrange(HERO)

save(df,file="scraped_skills_data.Rda")
```
